version: '3.8'

services:
  swagger:
    image: swaggerapi/swagger-ui
    environment:
      API_URL: /swagger.yaml
      BASE_URL: /
    env_file: .env
    volumes:
      - ./docs/openapi.yaml:/usr/share/nginx/html/swagger.yaml
    ports:
      - 3200:8080
