openapi: 3.0.3
info:
  title: Petstore API overview
  version: 1.0.0
servers:
  - url: https://plq2hxotz1.execute-api.ap-northeast-1.amazonaws.com/
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: For more information, see https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-userpools-server-contract-reference.html
      flows:
        authorizationCode:
          authorizationUrl: https://cdk-demo-apigw.auth.ap-northeast-1.amazoncognito.com/oauth2/authorize
          tokenUrl: https://cdk-demo-apigw.auth.ap-northeast-1.amazoncognito.com/oauth2/token
          scopes:
            openid: openid token
paths:
  /pets:
    get:
      operationId: listPets
      security:
        - OAuth2: [ openid, token ]
      responses:
        200:
          description: 200 OK
          content:
            application/json:
              schema:
                required:
                  - pets
                properties:
                  pets:
                    type: array
                    items:
                      required:
                        - name
                        - age
                      properties:
                        name:
                          type: string
                        age:
                          type: number
                example:
                  pets:
                    - name: hina
                      age: 1
                    - name: koharu
                      age: 2
                    - name: konatsu
                      age: 3
